package PARY.entity.constantes;

public enum Constant_RegAcciones {
    ELIMINACION, ACTUALIZACION, CREACION, RESERVACION, CANCELACION, APROBACION, CAMBIO_ESTADO_H, CAMBIO_ESTADO_N, CAMBIO_ESTADO_P
}
